In [1]:
import numpy as np

In [2]:
a = np.arange(0,80,10)

In [3]:
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [4]:
indices = [1,2,-3]

In [5]:
y = a[indices]

In [6]:
y

array([10, 20, 50])

In [7]:
print(y)


[10 20 50]


In [8]:
mask = np.array([0,1,1,0,0,1,0,0],dtype=bool)

In [9]:
mask


array([False,  True,  True, False, False,  True, False, False])

In [10]:
mask2 = a < 30

In [11]:
mask2

array([ True,  True,  True, False, False, False, False, False])

In [12]:
y = a[mask]


In [13]:
y

array([10, 20, 50])

In [14]:
z = a[mask2]


In [15]:
z

array([ 0, 10, 20])

In [16]:
a = np.array([3,-1,-2,4,-6,8])

In [17]:
a

array([ 3, -1, -2,  4, -6,  8])

In [18]:
a < 0

array([False,  True,  True, False,  True, False])

In [19]:
negatives = a< 0


In [20]:
negatives

array([False,  True,  True, False,  True, False])

In [21]:
a[negatives]

array([-1, -2, -6])

In [22]:
a[a<0]

array([-1, -2, -6])

In [23]:
a[a<0] = 0

In [24]:
a


array([3, 0, 0, 4, 0, 8])

In [25]:
(a < 3).any()

True

In [26]:
(a<3).all()

False

In [27]:
(a>3) & (a<8)

array([False, False, False,  True, False, False])

In [29]:
a[(a>3) & (a<8)]

array([4])

In [30]:
a

array([3, 0, 0, 4, 0, 8])

In [31]:
a.sort()

In [32]:
a

array([0, 0, 0, 3, 4, 8])

In [33]:
a = np.array([10,1,20])
b= np.array([2,3,20])

In [34]:
a

array([10,  1, 20])

In [35]:
b

array([ 2,  3, 20])

In [36]:
a > b

array([ True, False, False])

In [37]:
a[a>b]

array([10])

In [38]:
b[a>b]

array([2])

In [39]:
(a>b).dtype

dtype('bool')

In [40]:
a = np.array([10,1,20])

In [41]:
a

array([10,  1, 20])

In [42]:
subset = a[[0,2]]

In [43]:
subset

array([10, 20])

In [44]:
a.flags.owndata

True

In [45]:
subset.flags.owndata

True

In [46]:
a is subset

False

In [47]:
subset is a

False

In [48]:
subset[0] = -1


In [49]:
subset

array([-1, 20])

In [50]:
a

array([10,  1, 20])

In [51]:
a = np.arange(25).reshape(5,5)

In [52]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
a % 3 == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [54]:
a[a % 3 == 0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])