In [1]:
a = [1,2,3,4]
b = [11,12,13,14]

In [2]:
output = []

In [3]:
for item1, item2 in zip(a,b):
    output.append(item1 + item2)
    

In [4]:
output

[12, 14, 16, 18]

In [5]:
g = list(range(1000000))

In [6]:
%timeit sum(g)

100 loops, best of 3: 10.8 ms per loop


In [7]:
import numpy as np

In [8]:
g_array = np.array(g)

In [9]:
%timeit np.sum(g_array)

The slowest run took 18.40 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 1.05 ms per loop


In [10]:
%timeit g_array.sum()

1000 loops, best of 3: 1.04 ms per loop


In [11]:
a = np.array([1,2,3,4])
b = np.array([10,11,12,13])

In [12]:
a

array([1, 2, 3, 4])

In [13]:
b

array([10, 11, 12, 13])

In [14]:
a + b

array([11, 13, 15, 17])

In [15]:
a - b 

array([-9, -9, -9, -9])

In [16]:
a / b

array([0.1       , 0.18181818, 0.25      , 0.30769231])

In [17]:
a * b

array([10, 22, 36, 52])

In [18]:
a **b

array([       1,     2048,   531441, 67108864])

In [19]:
a = np.array([0,1,2,3])

In [20]:
type(a)

numpy.ndarray

In [21]:
a.dtype

dtype('int64')

In [22]:
a.size

4

In [23]:
a.ndim

1

In [24]:
a.shape

(4,)

In [25]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [26]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [27]:
np.log(a)

/usr/lib/python3/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229])

In [28]:
np.log

<ufunc 'log'>

In [29]:
np.sum

<function numpy.sum>

In [30]:
a.dtype

dtype('int64')

In [31]:
a[0]

0

In [32]:
a[0] = 10.6
a[0]

10

In [33]:
a.fill(-7.8)

In [34]:
a

array([-7, -7, -7, -7])

In [35]:
a = np.array([1,2,3,4],dtype=np.float)
a

array([1., 2., 3., 4.])

In [36]:
a.dtype

dtype('float64')

In [37]:
c = np.array([[10,11,12],[20,21,22]])

In [38]:
c

array([[10, 11, 12],
       [20, 21, 22]])

In [39]:
 c.dtype

dtype('int64')

In [40]:
c.ndim

2

In [41]:
c.shape

(2, 3)

In [42]:
a

array([1., 2., 3., 4.])

In [43]:
a.T

array([1., 2., 3., 4.])

In [44]:
c.size

6

In [45]:
c.nbytes

48

In [46]:
c[0]

array([10, 11, 12])

In [47]:
c[1]

array([20, 21, 22])

In [48]:
c[0,0]

10

In [49]:
c[0][0]

10